In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\sozma\OneDrive\Attachments\Documents\A1.data analyst course\pandas\countries of the world.csv")

In [4]:
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [8]:
df2=pd.read_table(r"C:\Users\sozma\OneDrive\Attachments\Documents\A1.data analyst course\pandas\countries of the world.txt")

In [9]:
df2

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [10]:
df3=pd.read_json(r"C:\Users\sozma\OneDrive\Attachments\Documents\A1.data analyst course\pandas\json_sample.json")

In [11]:
df3

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [12]:
df4=pd.read_excel(r"C:\Users\sozma\OneDrive\Attachments\Documents\A1.data analyst course\pandas\world_population_excel_workbook.xlsx")

In [13]:
df4

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [14]:
pd.set_option('display.max_rows', 235)
pd.set_option('display.max_columns', 40)

In [15]:
print(df)

                               Country                               Region
0                         Afghanistan         ASIA (EX. NEAR EAST)
1                             Albania   EASTERN EUROPE
2                             Algeria   NORTHERN AFRICA
3                      American Samoa   OCEANIA
4                             Andorra   WESTERN EUROPE
5                              Angola   SUB-SAHARAN AFRICA
6                            Anguilla               LATIN AMER. & CARIB
7                   Antigua & Barbuda               LATIN AMER. & CARIB
8                           Argentina               LATIN AMER. & CARIB
9                             Armenia                  C.W. OF IND. STATES
10                              Aruba               LATIN AMER. & CARIB
11                          Australia   OCEANIA
12                            Austria   WESTERN EUROPE
13                         Azerbaijan                  C.W. OF IND. STATES
14                       Bahamas, The               LATIN AMER. & CARIB
15                            Bahrain   NEAR EAST
16                         Bangladesh         ASIA (EX. NEAR EAST)
17                           Barbados               LATIN AMER. & CARIB
18                            Belarus                  C.W. OF IND. STATES
19                            Belgium   WESTERN EUROPE
20                             Belize               LATIN AMER. & CARIB
21                              Benin   SUB-SAHARAN AFRICA
22                            Bermuda   NORTHERN AMERICA
23                             Bhutan         ASIA (EX. NEAR EAST)
24                            Bolivia               LATIN AMER. & CARIB
25               Bosnia & Herzegovina   EASTERN EUROPE
26                           Botswana   SUB-SAHARAN AFRICA
27                             Brazil               LATIN AMER. & CARIB
28                 British Virgin Is.               LATIN AMER. & CARIB
29                             Brunei         ASIA (EX. NEAR EAST)
30                           Bulgaria   EASTERN EUROPE
31                       Burkina Faso   SUB-SAHARAN AFRICA
32                              Burma         ASIA (EX. NEAR EAST)
33                            Burundi   SUB-SAHARAN AFRICA
34                           Cambodia         ASIA (EX. NEAR EAST)
35                           Cameroon   SUB-SAHARAN AFRICA
36                             Canada   NORTHERN AMERICA
37                         Cape Verde   SUB-SAHARAN AFRICA
38                     Cayman Islands               LATIN AMER. & CARIB
39               Central African Rep.   SUB-SAHARAN AFRICA
40                               Chad   SUB-SAHARAN AFRICA
41                              Chile               LATIN AMER. & CARIB
42                              China         ASIA (EX. NEAR EAST)
43                           Colombia               LATIN AMER. & CARIB
44                            Comoros   SUB-SAHARAN AFRICA
45                   Congo, Dem. Rep.   SUB-SAHARAN AFRICA
46               Congo, Repub. of the   SUB-SAHARAN AFRICA
47                       Cook Islands   OCEANIA
48                         Costa Rica               LATIN AMER. & CARIB
49                      Cote d'Ivoire   SUB-SAHARAN AFRICA
50                            Croatia   EASTERN EUROPE
51                               Cuba               LATIN AMER. & CARIB
52                             Cyprus   NEAR EAST
53                     Czech Republic   EASTERN EUROPE
54                            Denmark   WESTERN EUROPE
55                           Djibouti   SUB-SAHARAN AFRICA
56                           Dominica               LATIN AMER. & CARIB
57                 Dominican Republic               LATIN AMER. & CARIB
58                         East Timor         ASIA (EX. NEAR EAST)
59                            Ecuador               LATIN AMER. & CARIB
60                              Egypt   NORTHERN AFRICA
61                        El Salvador               LATIN AMER. & CARIB
62                  Equatorial Guinea   SUB-SAHARAN AFRICA
63                            Eritrea   SUB-SAHARAN AFRICA
64                            Estonia   BALTICS
65                           Ethiopia   SUB-SAHARAN AFRICA
66                      Faroe Islands   WESTERN EUROPE
67                               Fiji   OCEANIA
68                            Finland   WESTERN EUROPE
69                             France   WESTERN EUROPE
70                      French Guiana               LATIN AMER. & CARIB
71                   French Polynesia   OCEANIA
72                              Gabon   SUB-SAHARAN AFRICA
73                        Gambia, The   SUB-SAHARAN AFRICA
74                         Gaza Strip   NEAR EAST
75                            Georgia                  C.W. OF IND. STATES
76                            Germany   WESTERN EUROPE
77                              Ghana   SUB-SAHARAN AFRICA
78                          Gibraltar   WESTERN EUROPE
79                             Greece   WESTERN EUROPE
80                          Greenland   NORTHERN AMERICA
81                            Grenada               LATIN AMER. & CARIB
82                         Guadeloupe               LATIN AMER. & CARIB
83                               Guam   OCEANIA
84                          Guatemala               LATIN AMER. & CARIB
85                           Guernsey   WESTERN EUROPE
86                             Guinea   SUB-SAHARAN AFRICA
87                      Guinea-Bissau   SUB-SAHARAN AFRICA
88                             Guyana               LATIN AMER. & CARIB
89                              Haiti               LATIN AMER. & CARIB
90                           Honduras               LATIN AMER. & CARIB
91                          Hong Kong         ASIA (EX. NEAR EAST)
92                            Hungary   EASTERN EUROPE
93                            Iceland   WESTERN EUROPE
94                              India         ASIA (EX. NEAR EAST)
95                          Indonesia         ASIA (EX. NEAR EAST)
96                               Iran         ASIA (EX. NEAR EAST)
97                               Iraq   NEAR EAST
98                            Ireland   WESTERN EUROPE
99                        Isle of Man   WESTERN EUROPE
100                            Israel   NEAR EAST
101                             Italy   WESTERN EUROPE
102                           Jamaica               LATIN AMER. & CARIB
103                             Japan         ASIA (EX. NEAR EAST)
104                            Jersey   WESTERN EUROPE
105                            Jordan   NEAR EAST
106                        Kazakhstan                  C.W. OF IND. STATES
107                             Kenya   SUB-SAHARAN AFRICA
108                          Kiribati   OCEANIA
109                      Korea, North         ASIA (EX. NEAR EAST)
110                      Korea, South         ASIA (EX. NEAR EAST)
111                            Kuwait   NEAR EAST
112                        Kyrgyzstan                  C.W. OF IND. STATES
113                              Laos         ASIA (EX. NEAR EAST)
114                            Latvia   BALTICS
115                           Lebanon   NEAR EAST
116                           Lesotho   SUB-SAHARAN AFRICA
117                           Liberia   SUB-SAHARAN AFRICA
118                             Libya   NORTHERN AFRICA
119                     Liechtenstein   WESTERN EUROPE
120                         Lithuania   BALTICS
121                        Luxembourg   WESTERN EUROPE
122                             Macau         ASIA (EX. NEAR EAST)
123                         Macedonia   EASTERN EUROPE
124                        Madagascar   SUB-SAHARAN AFRICA
125                            Malawi   SUB-SAHARAN AFRICA
126                          Malaysia         ASIA (EX. NEAR EAST)
127                          Maldives         ASIA (EX. NEAR EAST)
128                              Mali   SUB-SAHARAN AFRICA
129                             Malta   WESTERN EUROPE
130                  Marshall Islands   OCEANIA
131                        Martinique               LATIN AMER. & CARIB
132                        Mauritania   SUB-SAHARAN AFRICA
133                         Mauritius   SUB-SAHARAN AFRICA
134                           Mayotte   SUB-SAHARAN AFRICA
135                            Mexico               LATIN AMER. & CARIB
136              Micronesia, Fed. St.   OCEANIA
137                           Moldova                  C.W. OF IND. STATES
138                            Monaco   WESTERN EUROPE
139                          Mongolia         ASIA (EX. NEAR EAST)
140                        Montserrat               LATIN AMER. & CARIB
141                           Morocco   NORTHERN AFRICA
142                        Mozambique   SUB-SAHARAN AFRICA
143                           Namibia   SUB-SAHARAN AFRICA
144                             Nauru   OCEANIA
145                             Nepal         ASIA (EX. NEAR EAST)
146                       Netherlands   WESTERN EUROPE
147              Netherlands Antilles               LATIN AMER. & CARIB
148                     New Caledonia   OCEANIA
149                       New Zealand   OCEANIA
150                         Nicaragua               LATIN AMER. & CARIB
151                             Niger   SUB-SAHARAN AFRICA
152                           Nigeria   SUB-SAHARAN AFRICA
153                N. Mariana Islands   OCEANIA
154                            Norway   WESTERN EUROPE
155                              Oman   NEAR EAST
156                          Pakistan         ASIA (EX. NEAR EAST)
157                             Palau   OCEANIA
158                            Panama               LATIN AMER. & CARIB
159                  Papua New Guinea   OCEANIA
160                          Paraguay               LATIN AMER. & CARIB
161                              Peru               LATIN AMER. & CARIB
162                       Philippines         ASIA (EX. NEAR EAST)
163                            Poland   EASTERN EUROPE
164                          Portugal   WESTERN EUROPE
165                       Puerto Rico               LATIN AMER. & CARIB
166                             Qatar   NEAR EAST
167                           Reunion   SUB-SAHARAN AFRICA
168                           Romania   EASTERN EUROPE
169                            Russia                  C.W. OF IND. STATES
170                            Rwanda   SUB-SAHARAN AFRICA
171                      Saint Helena   SUB-SAHARAN AFRICA
172               Saint Kitts & Nevis               LATIN AMER. & CARIB
173                       Saint Lucia               LATIN AMER. & CARIB
174              St Pierre & Miquelon   NORTHERN AMERICA
175  Saint Vincent and the Grenadines               LATIN AMER. & CARIB
176                             Samoa   OCEANIA
177                        San Marino   WESTERN EUROPE
178               Sao Tome & Principe   SUB-SAHARAN AFRICA
179                      Saudi Arabia   NEAR EAST
180                           Senegal   SUB-SAHARAN AFRICA
181                            Serbia   EASTERN EUROPE
182                        Seychelles   SUB-SAHARAN AFRICA
183                      Sierra Leone   SUB-SAHARAN AFRICA
184                         Singapore         ASIA (EX. NEAR EAST)
185                          Slovakia   EASTERN EUROPE
186                          Slovenia   EASTERN EUROPE
187                   Solomon Islands   OCEANIA
188                           Somalia   SUB-SAHARAN AFRICA
189                      South Africa   SUB-SAHARAN AFRICA
190                             Spain   WESTERN EUROPE
191                         Sri Lanka         ASIA (EX. NEAR EAST)
192                             Sudan   SUB-SAHARAN AFRICA
193                          Suriname               LATIN AMER. & CARIB
194                         Swaziland   SUB-SAHARAN AFRICA
195                            Sweden   WESTERN EUROPE
196                       Switzerland   WESTERN EUROPE
197                             Syria   NEAR EAST
198                            Taiwan         ASIA (EX. NEAR EAST)
199                        Tajikistan                  C.W. OF IND. STATES
200                          Tanzania   SUB-SAHARAN AFRICA
201                          Thailand         ASIA (EX. NEAR EAST)
202                              Togo   SUB-SAHARAN AFRICA
203                             Tonga   OCEANIA
204                 Trinidad & Tobago               LATIN AMER. & CARIB
205                           Tunisia   NORTHERN AFRICA
206                            Turkey   NEAR EAST
207                      Turkmenistan                  C.W. OF IND. STATES
208                 Turks & Caicos Is               LATIN AMER. & CARIB
209                            Tuvalu   OCEANIA
210                            Uganda   SUB-SAHARAN AFRICA
211                           Ukraine                  C.W. OF IND. STATES
212              United Arab Emirates   NEAR EAST
213                    United Kingdom   WESTERN EUROPE
214                     United States   NORTHERN AMERICA
215                           Uruguay               LATIN AMER. & CARIB
216                        Uzbekistan                  C.W. OF IND. STATES
217                           Vanuatu   OCEANIA
218                         Venezuela               LATIN AMER. & CARIB
219                           Vietnam         ASIA (EX. NEAR EAST)
220                    Virgin Islands               LATIN AMER. & CARIB
221                 Wallis and Futuna   OCEANIA
222                         West Bank   NEAR EAST
223                    Western Sahara   NORTHERN AFRICA
224                             Yemen   NEAR EAST
225                            Zambia   SUB-SAHARAN AFRICA
226                          Zimbabwe   SUB-SAHARAN AFRICA

In [16]:
print(df2)

                               Country                               Region
0                         Afghanistan         ASIA (EX. NEAR EAST)
1                             Albania   EASTERN EUROPE
2                             Algeria   NORTHERN AFRICA
3                      American Samoa   OCEANIA
4                             Andorra   WESTERN EUROPE
5                              Angola   SUB-SAHARAN AFRICA
6                            Anguilla               LATIN AMER. & CARIB
7                   Antigua & Barbuda               LATIN AMER. & CARIB
8                           Argentina               LATIN AMER. & CARIB
9                             Armenia                  C.W. OF IND. STATES
10                              Aruba               LATIN AMER. & CARIB
11                          Australia   OCEANIA
12                            Austria   WESTERN EUROPE
13                         Azerbaijan                  C.W. OF IND. STATES
14                       Bahamas, The               LATIN AMER. & CARIB
15                            Bahrain   NEAR EAST
16                         Bangladesh         ASIA (EX. NEAR EAST)
17                           Barbados               LATIN AMER. & CARIB
18                            Belarus                  C.W. OF IND. STATES
19                            Belgium   WESTERN EUROPE
20                             Belize               LATIN AMER. & CARIB
21                              Benin   SUB-SAHARAN AFRICA
22                            Bermuda   NORTHERN AMERICA
23                             Bhutan         ASIA (EX. NEAR EAST)
24                            Bolivia               LATIN AMER. & CARIB
25               Bosnia & Herzegovina   EASTERN EUROPE
26                           Botswana   SUB-SAHARAN AFRICA
27                             Brazil               LATIN AMER. & CARIB
28                 British Virgin Is.               LATIN AMER. & CARIB
29                             Brunei         ASIA (EX. NEAR EAST)
30                           Bulgaria   EASTERN EUROPE
31                       Burkina Faso   SUB-SAHARAN AFRICA
32                              Burma         ASIA (EX. NEAR EAST)
33                            Burundi   SUB-SAHARAN AFRICA
34                           Cambodia         ASIA (EX. NEAR EAST)
35                           Cameroon   SUB-SAHARAN AFRICA
36                             Canada   NORTHERN AMERICA
37                         Cape Verde   SUB-SAHARAN AFRICA
38                     Cayman Islands               LATIN AMER. & CARIB
39               Central African Rep.   SUB-SAHARAN AFRICA
40                               Chad   SUB-SAHARAN AFRICA
41                              Chile               LATIN AMER. & CARIB
42                              China         ASIA (EX. NEAR EAST)
43                           Colombia               LATIN AMER. & CARIB
44                            Comoros   SUB-SAHARAN AFRICA
45                   Congo, Dem. Rep.   SUB-SAHARAN AFRICA
46               Congo, Repub. of the   SUB-SAHARAN AFRICA
47                       Cook Islands   OCEANIA
48                         Costa Rica               LATIN AMER. & CARIB
49                      Cote d'Ivoire   SUB-SAHARAN AFRICA
50                            Croatia   EASTERN EUROPE
51                               Cuba               LATIN AMER. & CARIB
52                             Cyprus   NEAR EAST
53                     Czech Republic   EASTERN EUROPE
54                            Denmark   WESTERN EUROPE
55                           Djibouti   SUB-SAHARAN AFRICA
56                           Dominica               LATIN AMER. & CARIB
57                 Dominican Republic               LATIN AMER. & CARIB
58                         East Timor         ASIA (EX. NEAR EAST)
59                            Ecuador               LATIN AMER. & CARIB
60                              Egypt   NORTHERN AFRICA
61                        El Salvador               LATIN AMER. & CARIB
62                  Equatorial Guinea   SUB-SAHARAN AFRICA
63                            Eritrea   SUB-SAHARAN AFRICA
64                            Estonia   BALTICS
65                           Ethiopia   SUB-SAHARAN AFRICA
66                      Faroe Islands   WESTERN EUROPE
67                               Fiji   OCEANIA
68                            Finland   WESTERN EUROPE
69                             France   WESTERN EUROPE
70                      French Guiana               LATIN AMER. & CARIB
71                   French Polynesia   OCEANIA
72                              Gabon   SUB-SAHARAN AFRICA
73                        Gambia, The   SUB-SAHARAN AFRICA
74                         Gaza Strip   NEAR EAST
75                            Georgia                  C.W. OF IND. STATES
76                            Germany   WESTERN EUROPE
77                              Ghana   SUB-SAHARAN AFRICA
78                          Gibraltar   WESTERN EUROPE
79                             Greece   WESTERN EUROPE
80                          Greenland   NORTHERN AMERICA
81                            Grenada               LATIN AMER. & CARIB
82                         Guadeloupe               LATIN AMER. & CARIB
83                               Guam   OCEANIA
84                          Guatemala               LATIN AMER. & CARIB
85                           Guernsey   WESTERN EUROPE
86                             Guinea   SUB-SAHARAN AFRICA
87                      Guinea-Bissau   SUB-SAHARAN AFRICA
88                             Guyana               LATIN AMER. & CARIB
89                              Haiti               LATIN AMER. & CARIB
90                           Honduras               LATIN AMER. & CARIB
91                          Hong Kong         ASIA (EX. NEAR EAST)
92                            Hungary   EASTERN EUROPE
93                            Iceland   WESTERN EUROPE
94                              India         ASIA (EX. NEAR EAST)
95                          Indonesia         ASIA (EX. NEAR EAST)
96                               Iran         ASIA (EX. NEAR EAST)
97                               Iraq   NEAR EAST
98                            Ireland   WESTERN EUROPE
99                        Isle of Man   WESTERN EUROPE
100                            Israel   NEAR EAST
101                             Italy   WESTERN EUROPE
102                           Jamaica               LATIN AMER. & CARIB
103                             Japan         ASIA (EX. NEAR EAST)
104                            Jersey   WESTERN EUROPE
105                            Jordan   NEAR EAST
106                        Kazakhstan                  C.W. OF IND. STATES
107                             Kenya   SUB-SAHARAN AFRICA
108                          Kiribati   OCEANIA
109                      Korea, North         ASIA (EX. NEAR EAST)
110                      Korea, South         ASIA (EX. NEAR EAST)
111                            Kuwait   NEAR EAST
112                        Kyrgyzstan                  C.W. OF IND. STATES
113                              Laos         ASIA (EX. NEAR EAST)
114                            Latvia   BALTICS
115                           Lebanon   NEAR EAST
116                           Lesotho   SUB-SAHARAN AFRICA
117                           Liberia   SUB-SAHARAN AFRICA
118                             Libya   NORTHERN AFRICA
119                     Liechtenstein   WESTERN EUROPE
120                         Lithuania   BALTICS
121                        Luxembourg   WESTERN EUROPE
122                             Macau         ASIA (EX. NEAR EAST)
123                         Macedonia   EASTERN EUROPE
124                        Madagascar   SUB-SAHARAN AFRICA
125                            Malawi   SUB-SAHARAN AFRICA
126                          Malaysia         ASIA (EX. NEAR EAST)
127                          Maldives         ASIA (EX. NEAR EAST)
128                              Mali   SUB-SAHARAN AFRICA
129                             Malta   WESTERN EUROPE
130                  Marshall Islands   OCEANIA
131                        Martinique               LATIN AMER. & CARIB
132                        Mauritania   SUB-SAHARAN AFRICA
133                         Mauritius   SUB-SAHARAN AFRICA
134                           Mayotte   SUB-SAHARAN AFRICA
135                            Mexico               LATIN AMER. & CARIB
136              Micronesia, Fed. St.   OCEANIA
137                           Moldova                  C.W. OF IND. STATES
138                            Monaco   WESTERN EUROPE
139                          Mongolia         ASIA (EX. NEAR EAST)
140                        Montserrat               LATIN AMER. & CARIB
141                           Morocco   NORTHERN AFRICA
142                        Mozambique   SUB-SAHARAN AFRICA
143                           Namibia   SUB-SAHARAN AFRICA
144                             Nauru   OCEANIA
145                             Nepal         ASIA (EX. NEAR EAST)
146                       Netherlands   WESTERN EUROPE
147              Netherlands Antilles               LATIN AMER. & CARIB
148                     New Caledonia   OCEANIA
149                       New Zealand   OCEANIA
150                         Nicaragua               LATIN AMER. & CARIB
151                             Niger   SUB-SAHARAN AFRICA
152                           Nigeria   SUB-SAHARAN AFRICA
153                N. Mariana Islands   OCEANIA
154                            Norway   WESTERN EUROPE
155                              Oman   NEAR EAST
156                          Pakistan         ASIA (EX. NEAR EAST)
157                             Palau   OCEANIA
158                            Panama               LATIN AMER. & CARIB
159                  Papua New Guinea   OCEANIA
160                          Paraguay               LATIN AMER. & CARIB
161                              Peru               LATIN AMER. & CARIB
162                       Philippines         ASIA (EX. NEAR EAST)
163                            Poland   EASTERN EUROPE
164                          Portugal   WESTERN EUROPE
165                       Puerto Rico               LATIN AMER. & CARIB
166                             Qatar   NEAR EAST
167                           Reunion   SUB-SAHARAN AFRICA
168                           Romania   EASTERN EUROPE
169                            Russia                  C.W. OF IND. STATES
170                            Rwanda   SUB-SAHARAN AFRICA
171                      Saint Helena   SUB-SAHARAN AFRICA
172               Saint Kitts & Nevis               LATIN AMER. & CARIB
173                       Saint Lucia               LATIN AMER. & CARIB
174              St Pierre & Miquelon   NORTHERN AMERICA
175  Saint Vincent and the Grenadines               LATIN AMER. & CARIB
176                             Samoa   OCEANIA
177                        San Marino   WESTERN EUROPE
178               Sao Tome & Principe   SUB-SAHARAN AFRICA
179                      Saudi Arabia   NEAR EAST
180                           Senegal   SUB-SAHARAN AFRICA
181                            Serbia   EASTERN EUROPE
182                        Seychelles   SUB-SAHARAN AFRICA
183                      Sierra Leone   SUB-SAHARAN AFRICA
184                         Singapore         ASIA (EX. NEAR EAST)
185                          Slovakia   EASTERN EUROPE
186                          Slovenia   EASTERN EUROPE
187                   Solomon Islands   OCEANIA
188                           Somalia   SUB-SAHARAN AFRICA
189                      South Africa   SUB-SAHARAN AFRICA
190                             Spain   WESTERN EUROPE
191                         Sri Lanka         ASIA (EX. NEAR EAST)
192                             Sudan   SUB-SAHARAN AFRICA
193                          Suriname               LATIN AMER. & CARIB
194                         Swaziland   SUB-SAHARAN AFRICA
195                            Sweden   WESTERN EUROPE
196                       Switzerland   WESTERN EUROPE
197                             Syria   NEAR EAST
198                            Taiwan         ASIA (EX. NEAR EAST)
199                        Tajikistan                  C.W. OF IND. STATES
200                          Tanzania   SUB-SAHARAN AFRICA
201                          Thailand         ASIA (EX. NEAR EAST)
202                              Togo   SUB-SAHARAN AFRICA
203                             Tonga   OCEANIA
204                 Trinidad & Tobago               LATIN AMER. & CARIB
205                           Tunisia   NORTHERN AFRICA
206                            Turkey   NEAR EAST
207                      Turkmenistan                  C.W. OF IND. STATES
208                 Turks & Caicos Is               LATIN AMER. & CARIB
209                            Tuvalu   OCEANIA
210                            Uganda   SUB-SAHARAN AFRICA
211                           Ukraine                  C.W. OF IND. STATES
212              United Arab Emirates   NEAR EAST
213                    United Kingdom   WESTERN EUROPE
214                     United States   NORTHERN AMERICA
215                           Uruguay               LATIN AMER. & CARIB
216                        Uzbekistan                  C.W. OF IND. STATES
217                           Vanuatu   OCEANIA
218                         Venezuela               LATIN AMER. & CARIB
219                           Vietnam         ASIA (EX. NEAR EAST)
220                    Virgin Islands               LATIN AMER. & CARIB
221                 Wallis and Futuna   OCEANIA
222                         West Bank   NEAR EAST
223                    Western Sahara   NORTHERN AFRICA
224                             Yemen   NEAR EAST
225                            Zambia   SUB-SAHARAN AFRICA
226                          Zimbabwe   SUB-SAHARAN AFRICA

In [17]:
print(df3)

                                           12 Strong  \
0  {'Genre': 'Action', 'Gross': '$453,173', 'IMDB...

            A Fantastic Woman (Una Mujer Fantástica)  \
0  {'popcornscore': 83, 'rating': 'R', 'tomatosco...

                          All The Money In The World  \
0  {'popcornscore': 71, 'rating': 'R', 'tomatosco...

                          Bilal: A New Breed Of Hero  \
0  {'popcornscore': 91, 'rating': 'PG13', 'tomato...

                                Call Me By Your Name  \
0  {'popcornscore': 87, 'rating': 'R', 'tomatosco...

                                        Darkest Hour  \
0  {'popcornscore': 84, 'rating': 'PG13', 'tomato...

                                      Den Of Thieves  \
0  {'Genre': 'Action', 'Gross': '$491,898', 'IMDB...

                                           Ferdinand  \
0  {'popcornscore': 49, 'rating': 'PG', 'tomatosc...

                                  Fifty Shades Freed  \
0  {'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...

                   Film Stars Don'T Die In Liverpool  \
0  {'popcornscore': 69, 'rating': 'R', 'tomatosco...

                                     Forever My Girl  \
0  {'popcornscore': 91, 'rating': 'PG', 'tomatosc...

                                        Golden Exits  \
0  {'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...

                                            Hostiles  \
0  {'Genre': 'Adventure', 'Gross': '$548,886', 'I...

                                            I, Tonya  \
0  {'popcornscore': 89, 'rating': 'R', 'tomatosco...

                             Insidious: The Last Key  \
0  {'popcornscore': 51, 'rating': 'PG13', 'tomato...

                      Jumanji: Welcome To The Jungle  \
0  {'Genre': 'Action', 'Gross': '$760,867', 'IMDB...

                         Mary And The Witch'S Flower  \
0  {'popcornscore': 78, 'rating': 'PG', 'tomatosc...

                         Maze Runner: The Death Cure  \
0  {'Genre': 'Action', 'Gross': '$720,463', 'IMDB...

                                        Molly'S Game  \
0  {'popcornscore': 85, 'rating': 'R', 'tomatosco...

                                        Paddington 2  \
0  {'Genre': 'Animation', 'Gross': '$184,414', 'I...

                                           Padmaavat  \
0  {'popcornscore': 62, 'rating': 'NR', 'tomatosc...

                                          Permission  \
0  {'Genre': 'Comedy', 'Gross': 'unknown', 'IMDB ...

                                        Peter Rabbit  \
0  {'Genre': 'Animation', 'Gross': 'unknown', 'IM...

                                      Phantom Thread  \
0  {'popcornscore': 68, 'rating': 'R', 'tomatosco...

                                     Pitch Perfect 3  \
0  {'popcornscore': 52, 'rating': 'PG13', 'tomato...

                                          Proud Mary  \
0  {'popcornscore': 56, 'rating': 'R', 'tomatosco...

                             Sanpo Suru Shinryakusha  \
0  {'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...

                            Star Wars: The Last Jedi  \
0  {'popcornscore': 48, 'rating': 'PG13', 'tomato...

                                  The 15:17 To Paris  \
0  {'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...

                                        The Commuter  \
0  {'popcornscore': 48, 'rating': 'PG13', 'tomato...

                                 The Disaster Artist  \
0  {'popcornscore': 89, 'rating': 'R', 'tomatosco...

                                The Greatest Showman  \
0  {'Genre': 'Biography', 'Gross': '$627,248', 'I...

                              The Insult (L'Insulte)  \
0  {'popcornscore': 86, 'rating': 'R', 'tomatosco...

                                            The Post  \
0  {'Genre': 'Biography', 'Gross': '$463,228', 'I...

                                  The Shape Of Water  \
0  {'Genre': 'Adventure', 'Gross': '$448,287', 'I...

           Three Billboards Outside Ebbing, Missouri  \
0  {'popcornscore': 87, 'rating': 'R', 'tomatosco...

                           Till The End Of The World  \
0  {'popcornscore': -1, 'rating': 'NR', 'tomatosc...

                                          Winchester
0  {'Genre': 'Biography', 'Gross': '$696,786', 'I...

In [18]:
print(df4)

     Rank CCA3                           Country              Capital  \
0      36  AFG                       Afghanistan                Kabul
1     138  ALB                           Albania               Tirana
2      34  DZA                           Algeria              Algiers
3     213  ASM                    American Samoa            Pago Pago
4     203  AND                           Andorra     Andorra la Vella
5      42  AGO                            Angola               Luanda
6     224  AIA                          Anguilla           The Valley
7     201  ATG               Antigua and Barbuda       Saint Johnâ€™s
8      33  ARG                         Argentina         Buenos Aires
9     140  ARM                           Armenia              Yerevan
10    198  ABW                             Aruba           Oranjestad
11     55  AUS                         Australia             Canberra
12     99  AUT                           Austria               Vienna
13     91  AZE                        Azerbaijan                 Baku
14    176  BHS                           Bahamas               Nassau
15    154  BHR                           Bahrain               Manama
16      8  BGD                        Bangladesh                Dhaka
17    186  BRB                          Barbados           Bridgetown
18     96  BLR                           Belarus                Minsk
19     81  BEL                           Belgium             Brussels
20    177  BLZ                            Belize             Belmopan
21     77  BEN                             Benin           Porto-Novo
22    206  BMU                           Bermuda             Hamilton
23    165  BTN                            Bhutan              Thimphu
24     80  BOL                           Bolivia                Sucre
25    137  BIH            Bosnia and Herzegovina             Sarajevo
26    144  BWA                          Botswana             Gaborone
27      7  BRA                            Brazil             Brasilia
28    221  VGB            British Virgin Islands            Road Town
29    175  BRN                            Brunei  Bandar Seri Begawan
30    108  BGR                          Bulgaria                Sofia
31     58  BFA                      Burkina Faso          Ouagadougou
32     78  BDI                           Burundi            Bujumbura
33     73  KHM                          Cambodia           Phnom Penh
34     53  CMR                          Cameroon              Yaounde
35     39  CAN                            Canada               Ottawa
36    171  CPV                        Cape Verde                Praia
37    205  CYM                    Cayman Islands          George Town
38    117  CAF          Central African Republic               Bangui
39     69  TCD                              Chad            N'Djamena
40     65  CHL                             Chile             Santiago
41      1  CHN                             China              Beijing
42     28  COL                          Colombia               Bogota
43    163  COM                           Comoros               Moroni
44    223  COK                      Cook Islands               Avarua
45    124  CRI                        Costa Rica            San JosÃ©
46    130  HRV                           Croatia               Zagreb
47     85  CUB                              Cuba               Havana
48    189  CUW                           Curacao           Willemstad
49    158  CYP                            Cyprus              Nicosia
50     88  CZE                    Czech Republic               Prague
51    115  DNK                           Denmark           Copenhagen
52    160  DJI                          Djibouti             Djibouti
53    204  DMA                          Dominica               Roseau
54     84  DOM                Dominican Republic        Santo Domingo
55     15  COD                          DR Congo             Kinshasa
56     67  ECU                           Ecuador                Quito
57     14  EGY                             Egypt                Cairo
58    112  SLV                       El Salvador         San Salvador
59    152  GNQ                 Equatorial Guinea               Malabo
60    132  ERI                           Eritrea               Asmara
61    156  EST                           Estonia              Tallinn
62    159  SWZ                          Eswatini              Mbabane
63     12  ETH                          Ethiopia          Addis Ababa
64    231  FLK                  Falkland Islands              Stanley
65    209  FRO                     Faroe Islands            TÃ³rshavn
66    162  FJI                              Fiji                 Suva
67    118  FIN                           Finland             Helsinki
68     23  FRA                            France                Paris
69    184  GUF                     French Guiana              Cayenne
70    183  PYF                  French Polynesia              Papeete
71    146  GAB                             Gabon           Libreville
72    142  GMB                            Gambia               Banjul
73    131  GEO                           Georgia              Tbilisi
74     19  DEU                           Germany               Berlin
75     47  GHA                             Ghana                Accra
76    219  GIB                         Gibraltar            Gibraltar
77     90  GRC                            Greece               Athens
78    208  GRL                         Greenland                 Nuuk
79    193  GRD                           Grenada       Saint George's
80    178  GLP                        Guadeloupe          Basse-Terre
81    191  GUM                              Guam            HagÃ¥tÃ±a
82     68  GTM                         Guatemala       Guatemala City
83    207  GGY                          Guernsey     Saint Peter Port
84     75  GIN                            Guinea              Conakry
85    149  GNB                     Guinea-Bissau               Bissau
86    164  GUY                            Guyana           Georgetown
87     82  HTI                             Haiti       Port-au-Prince
88     89  HND                          Honduras          Tegucigalpa
89    104  HKG                         Hong Kong            Hong Kong
90     94  HUN                           Hungary             Budapest
91    179  ISL                           Iceland           ReykjavÃ­k
92      2  IND                             India            New Delhi
93      4  IDN                         Indonesia              Jakarta
94     17  IRN                              Iran               Tehran
95     35  IRQ                              Iraq              Baghdad
96    125  IRL                           Ireland               Dublin
97    202  IMN                       Isle of Man              Douglas
98     98  ISR                            Israel            Jerusalem
99     25  ITA                             Italy                 Rome
100    52  CIV                       Ivory Coast         Yamoussoukro
101   139  JAM                           Jamaica             Kingston
102    11  JPN                             Japan                Tokyo
103   195  JEY                            Jersey         Saint Helier
104    83  JOR                            Jordan                Amman
105    66  KAZ                        Kazakhstan            Nursultan
106    27  KEN                             Kenya              Nairobi
107   192  KIR                          Kiribati               Tarawa
108   129  KWT                            Kuwait          Kuwait City
109   110  KGZ                        Kyrgyzstan              Bishkek
110   103  LAO                              Laos            Vientiane
111   151  LVA                            Latvia                 Riga
112   119  LBN                           Lebanon               Beirut
113   147  LSO                           Lesotho               Maseru
114   121  LBR                           Liberia             Monrovia
115   107  LBY                             Libya              Tripoli
116   216  LIE                     Liechtenstein                Vaduz
117   141  LTU                         Lithuania              Vilnius
118   168  LUX                        Luxembourg           Luxembourg
119   167  MAC                             Macau    Concelho de Macau
120    50  MDG                        Madagascar         Antananarivo
121    62  MWI                            Malawi             Lilongwe
122    45  MYS                          Malaysia         Kuala Lumpur
123   174  MDV                          Maldives                MalÃ©
124    59  MLI                              Mali               Bamako
125   173  MLT                             Malta             Valletta
126   215  MHL                  Marshall Islands               Majuro
127   180  MTQ                        Martinique       Fort-de-France
128   126  MRT                        Mauritania           Nouakchott
129   157  MUS                         Mauritius           Port Louis
130   182  MYT                           Mayotte            Mamoudzou
131    10  MEX                            Mexico          Mexico City
132   194  FSM                        Micronesia              Palikir
133   135  MDA                           Moldova             Chisinau
134   217  MCO                            Monaco               Monaco
135   134  MNG                          Mongolia          Ulaanbaatar
136   169  MNE                        Montenegro            Podgorica
137   230  MSR                        Montserrat               Brades
138    40  MAR                           Morocco                Rabat
139    48  MOZ                        Mozambique               Maputo
140    26  MMR                           Myanmar          Nay Pyi Taw
141   145  NAM                           Namibia             Windhoek
142   225  NRU                             Nauru                Yaren
143    49  NPL                             Nepal            Kathmandu
144    71  NLD                       Netherlands            Amsterdam
145   185  NCL                     New Caledonia              NoumÃ©a
146   123  NZL                       New Zealand           Wellington
147   106  NIC                         Nicaragua              Managua
148    54  NER                             Niger               Niamey
149     6  NGA                           Nigeria                Abuja
150   232  NIU                              Niue                Alofi
151    56  PRK                       North Korea            Pyongyang
152   150  MKD                   North Macedonia               Skopje
153   210  NFK          Northern Mariana Islands               Saipan
154   120  NOR                            Norway                 Oslo
155   127  OMN                              Oman               Muscat
156     5  PAK                          Pakistan            Islamabad
157   222  PLW                             Palau            Ngerulmud
158   122  PSE                         Palestine             Ramallah
159   128  PAN                            Panama          Panama City
160    93  PNG                  Papua New Guinea         Port Moresby
161   109  PRY                          Paraguay            AsunciÃ³n
162    44  PER                              Peru                 Lima
163    13  PHL                       Philippines               Manila
164    37  POL                            Poland               Warsaw
165    92  PRT                          Portugal               Lisbon
166   136  PRI                       Puerto Rico             San Juan
167   143  QAT                             Qatar                 Doha
168   114  COG             Republic of the Congo          Brazzaville
169   161  REU                           Reunion          Saint-Denis
170    64  ROU                           Romania            Bucharest
171     9  RUS                            Russia               Moscow
172    76  RWA                            Rwanda               Kigali
173   228  BLM                  Saint Barthelemy             Gustavia
174   211  KNA             Saint Kitts and Nevis           Basseterre
175   190  LCA                       Saint Lucia             Castries
176   220  MAF                      Saint Martin              Marigot
177   229  SPM         Saint Pierre and Miquelon         Saint-Pierre
178   199  VCT  Saint Vincent and the Grenadines            Kingstown
179   188  WSM                             Samoa                 Apia
180   218  SMR                        San Marino           San Marino
181   187  STP             Sao Tome and Principe           SÃ£o TomÃ©
182    41  SAU                      Saudi Arabia               Riyadh
183    72  SEN                           Senegal                Dakar
184   105  SRB                            Serbia             Belgrade
185   196  SYC                        Seychelles             Victoria
186   102  SLE                      Sierra Leone             Freetown
187   113  SGP                         Singapore            Singapore
188   214  SXM                      Sint Maarten          Philipsburg
189   116  SVK                          Slovakia           Bratislava
190   148  SVN                          Slovenia            Ljubljana
191   166  SLB                   Solomon Islands              Honiara
192    70  SOM                           Somalia            Mogadishu
193    24  ZAF                      South Africa             Pretoria
194    29  KOR                       South Korea                Seoul
195    86  SSD                       South Sudan                 Juba
196    30  ESP                             Spain               Madrid
197    61  LKA                         Sri Lanka              Colombo
198    32  SDN                             Sudan             Khartoum
199   170  SUR                          Suriname           Paramaribo
200    87  SWE                            Sweden            Stockholm
201   101  CHE                       Switzerland                 Bern
202    60  SYR                             Syria             Damascus
203    57  TWN                            Taiwan               Taipei
204    95  TJK                        Tajikistan             Dushanbe
205    22  TZA                          Tanzania               Dodoma
206    20  THA                          Thailand              Bangkok
207   155  TLS                       Timor-Leste                 Dili
208   100  TGO                              Togo                LomÃ©
209   233  TKL                           Tokelau             Nukunonu
210   197  TON                             Tonga         Nukuâ€˜alofa
211   153  TTO               Trinidad and Tobago        Port-of-Spain
212    79  TUN                           Tunisia                Tunis
213    18  TUR                            Turkey               Ankara
214   111  TKM                      Turkmenistan             Ashgabat
215   212  TCA          Turks and Caicos Islands        Cockburn Town
216   227  TUV                            Tuvalu             Funafuti
217    31  UGA                            Uganda              Kampala
218    38  UKR                           Ukraine                 Kiev
219    97  ARE              United Arab Emirates            Abu Dhabi
220    21  GBR                    United Kingdom               London
221     3  USA                     United States     Washington, D.C.
222   200  VIR      United States Virgin Islands     Charlotte Amalie
223   133  URY                           Uruguay           Montevideo
224    43  UZB                        Uzbekistan             Tashkent
225   181  VUT                           Vanuatu            Port-Vila
226   234  VAT                      Vatican City         Vatican City
227    51  VEN                         Venezuela              Caracas
228    16  VNM                           Vietnam                Hanoi
229   226  WLF                 Wallis and Futuna             Mata-Utu
230   172  ESH                    Western Sahara            El AaiÃºn
231    46  YEM                             Yemen                Sanaa
232    63  ZMB                            Zambia               Lusaka
233    74  ZWE                          Zimbabwe               Harare

         Continent  2022 Population  2020 Population  2015 Population  \
0             Asia         41128771         38972230         33753499
1           Europe          2842321          2866849          2882481
2           Africa         44903225         43451666         39543154
3          Oceania            44273            46189            51368
4           Europe            79824            77700            71746
5           Africa         35588987         33428485         28127721
6    North America            15857            15585            14525
7    North America            93763            92664            89941
8    South America         45510318         45036032         43257065
9             Asia          2780469          2805608          2878595
10   North America           106445           106585           104257
11         Oceania         26177413         25670051         23820236
12          Europe          8939617          8907777          8642421
13            Asia         10358074         10284951          9863480
14   North America           409984           406471           392697
15            Asia          1472233          1477469          1362142
16            Asia        171186372        167420951        157830000
17   North America           281635           280693           278083
18          Europe          9534954          9633740          9700609
19          Europe         11655930         11561717         11248303
20   North America           405272           394921           359871
21          Africa         13352864         12643123         10932783
22   North America            64184            64031            63144
23            Asia           782455           772506           743274
24   South America         12224110         11936162         11090085
25          Europe          3233526          3318407          3524324
26          Africa          2630296          2546402          2305171
27   South America        215313498        213196304        205188205
28   North America            31305            30910            29366
29            Asia           449002           441725           421437
30          Europe          6781953          6979175          7309253
31          Africa         22673762         21522626         18718019
32          Africa         12889576         12220227         10727148
33            Asia         16767842         16396860         15417523
34          Africa         27914536         26491087         23012646
35   North America         38454327         37888705         35732126
36          Africa           593149           582640           552166
37   North America            68706            67311            60911
38          Africa          5579144          5343020          4819333
39          Africa         17723315         16644701         14140274
40   South America         19603733         19300315         17870124
41            Asia       1425887337       1424929781       1393715448
42   South America         51874024         50930662         47119728
43          Africa           836774           806166           730216
44         Oceania            17011            17029            17695
45   North America          5180829          5123105          4895242
46          Europe          4030358          4096868          4254815
47   North America         11212191         11300698         11339894
48   North America           191163           189288           169572

In [19]:
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    str
 2   Country                      234 non-null    str
 3   Capital                      234 non-null    str
 4   Continent                    234 non-null    str
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (kmÂ²)                  234 non-null    int64
 14  Density (per kmÂ²)           234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), str(4)
memory usage: 37.5 KB

In [20]:
df.shape

(227, 2)

In [21]:
df2.shape

(227, 2)

In [22]:
df3.shape

(1, 38)

In [23]:
df4.shape

(234, 17)

df.head()

In [24]:
df.head(10)

              Country                               Region
0        Afghanistan         ASIA (EX. NEAR EAST)
1            Albania   EASTERN EUROPE
2            Algeria   NORTHERN AFRICA
3     American Samoa   OCEANIA
4            Andorra   WESTERN EUROPE
5             Angola   SUB-SAHARAN AFRICA
6           Anguilla               LATIN AMER. & CARIB
7  Antigua & Barbuda               LATIN AMER. & CARIB
8          Argentina               LATIN AMER. & CARIB
9            Armenia                  C.W. OF IND. STATES

In [25]:
df2.head(10)

              Country                               Region
0        Afghanistan         ASIA (EX. NEAR EAST)
1            Albania   EASTERN EUROPE
2            Algeria   NORTHERN AFRICA
3     American Samoa   OCEANIA
4            Andorra   WESTERN EUROPE
5             Angola   SUB-SAHARAN AFRICA
6           Anguilla               LATIN AMER. & CARIB
7  Antigua & Barbuda               LATIN AMER. & CARIB
8          Argentina               LATIN AMER. & CARIB
9            Armenia                  C.W. OF IND. STATES

In [26]:
df3.head(10)

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,Forever My Girl,Golden Exits,Hostiles,"I, Tonya",Insidious: The Last Key,Jumanji: Welcome To The Jungle,Mary And The Witch'S Flower,Maze Runner: The Death Cure,Molly'S Game,Paddington 2,Padmaavat,Permission,Peter Rabbit,Phantom Thread,Pitch Perfect 3,Proud Mary,Sanpo Suru Shinryakusha,Star Wars: The Last Jedi,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'Genre': 'Adventure', 'Gross': '$548,886', 'I...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'popcornscore': 51, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$760,867', 'IMDB...","{'popcornscore': 78, 'rating': 'PG', 'tomatosc...","{'Genre': 'Action', 'Gross': '$720,463', 'IMDB...","{'popcornscore': 85, 'rating': 'R', 'tomatosco...","{'Genre': 'Animation', 'Gross': '$184,414', 'I...","{'popcornscore': 62, 'rating': 'NR', 'tomatosc...","{'Genre': 'Comedy', 'Gross': 'unknown', 'IMDB ...","{'Genre': 'Animation', 'Gross': 'unknown', 'IM...","{'popcornscore': 68, 'rating': 'R', 'tomatosco...","{'popcornscore': 52, 'rating': 'PG13', 'tomato...","{'popcornscore': 56, 'rating': 'R', 'tomatosco...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [27]:
df4.head(10)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
5,42,AGO,Angola,Luanda,Africa,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45
6,224,AIA,Anguilla,The Valley,North America,15857,15585,14525,13172,11047,8316,6560,6283,91,174.2527,1.0066,0.00
7,201,ATG,Antigua and Barbuda,Saint Johnâ€™s,North America,93763,92664,89941,85695,75055,63328,64888,64516,442,212.1335,1.0058,0.00
8,33,ARG,Argentina,Buenos Aires,South America,45510318,45036032,43257065,41100123,37070774,32637657,28024803,23842803,2780400,16.3683,1.0052,0.57
9,140,ARM,Armenia,Yerevan,Asia,2780469,2805608,2878595,2946293,3168523,3556539,3135123,2534377,29743,93.4831,0.9962,0.03

In [28]:
df.tail(10)

                Country                               Region
217            Vanuatu   OCEANIA
218          Venezuela               LATIN AMER. & CARIB
219            Vietnam         ASIA (EX. NEAR EAST)
220     Virgin Islands               LATIN AMER. & CARIB
221  Wallis and Futuna   OCEANIA
222          West Bank   NEAR EAST
223     Western Sahara   NORTHERN AFRICA
224              Yemen   NEAR EAST
225             Zambia   SUB-SAHARAN AFRICA
226           Zimbabwe   SUB-SAHARAN AFRICA

In [29]:
df2.tail(10)

                Country                               Region
217            Vanuatu   OCEANIA
218          Venezuela               LATIN AMER. & CARIB
219            Vietnam         ASIA (EX. NEAR EAST)
220     Virgin Islands               LATIN AMER. & CARIB
221  Wallis and Futuna   OCEANIA
222          West Bank   NEAR EAST
223     Western Sahara   NORTHERN AFRICA
224              Yemen   NEAR EAST
225             Zambia   SUB-SAHARAN AFRICA
226           Zimbabwe   SUB-SAHARAN AFRICA

In [30]:
df3.tail(10)

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,Forever My Girl,Golden Exits,Hostiles,"I, Tonya",Insidious: The Last Key,Jumanji: Welcome To The Jungle,Mary And The Witch'S Flower,Maze Runner: The Death Cure,Molly'S Game,Paddington 2,Padmaavat,Permission,Peter Rabbit,Phantom Thread,Pitch Perfect 3,Proud Mary,Sanpo Suru Shinryakusha,Star Wars: The Last Jedi,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'Genre': 'Adventure', 'Gross': '$548,886', 'I...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'popcornscore': 51, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$760,867', 'IMDB...","{'popcornscore': 78, 'rating': 'PG', 'tomatosc...","{'Genre': 'Action', 'Gross': '$720,463', 'IMDB...","{'popcornscore': 85, 'rating': 'R', 'tomatosco...","{'Genre': 'Animation', 'Gross': '$184,414', 'I...","{'popcornscore': 62, 'rating': 'NR', 'tomatosc...","{'Genre': 'Comedy', 'Gross': 'unknown', 'IMDB ...","{'Genre': 'Animation', 'Gross': 'unknown', 'IM...","{'popcornscore': 68, 'rating': 'R', 'tomatosco...","{'popcornscore': 52, 'rating': 'PG13', 'tomato...","{'popcornscore': 56, 'rating': 'R', 'tomatosco...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [31]:
df4.tail(3)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [33]:
print(df2['Region'])

0            ASIA (EX. NEAR EAST)
1      EASTERN EUROPE
2      NORTHERN AFRICA
3      OCEANIA
4      WESTERN EUROPE
5      SUB-SAHARAN AFRICA
6                  LATIN AMER. & CARIB
7                  LATIN AMER. & CARIB
8                  LATIN AMER. & CARIB
9                     C.W. OF IND. STATES
10                 LATIN AMER. & CARIB
11     OCEANIA
12     WESTERN EUROPE
13                    C.W. OF IND. STATES
14                 LATIN AMER. & CARIB
15     NEAR EAST
16           ASIA (EX. NEAR EAST)
17                 LATIN AMER. & CARIB
18                    C.W. OF IND. STATES
19     WESTERN EUROPE
20                 LATIN AMER. & CARIB
21     SUB-SAHARAN AFRICA
22     NORTHERN AMERICA
23           ASIA (EX. NEAR EAST)
24                 LATIN AMER. & CARIB
25     EASTERN EUROPE
26     SUB-SAHARAN AFRICA
27                 LATIN AMER. & CARIB
28                 LATIN AMER. & CARIB
29           ASIA (EX. NEAR EAST)
30     EASTERN EUROPE
31     SUB-SAHARAN AFRICA
32           ASIA (EX. NEAR EAST)
33     SUB-SAHARAN AFRICA
34           ASIA (EX. NEAR EAST)
35     SUB-SAHARAN AFRICA
36     NORTHERN AMERICA
37     SUB-SAHARAN AFRICA
38                 LATIN AMER. & CARIB
39     SUB-SAHARAN AFRICA
40     SUB-SAHARAN AFRICA
41                 LATIN AMER. & CARIB
42           ASIA (EX. NEAR EAST)
43                 LATIN AMER. & CARIB
44     SUB-SAHARAN AFRICA
45     SUB-SAHARAN AFRICA
46     SUB-SAHARAN AFRICA
47     OCEANIA
48                 LATIN AMER. & CARIB
49     SUB-SAHARAN AFRICA
50     EASTERN EUROPE
51                 LATIN AMER. & CARIB
52     NEAR EAST
53     EASTERN EUROPE
54     WESTERN EUROPE
55     SUB-SAHARAN AFRICA
56                 LATIN AMER. & CARIB
57                 LATIN AMER. & CARIB
58           ASIA (EX. NEAR EAST)
59                 LATIN AMER. & CARIB
60     NORTHERN AFRICA
61                 LATIN AMER. & CARIB
62     SUB-SAHARAN AFRICA
63     SUB-SAHARAN AFRICA
64     BALTICS
65     SUB-SAHARAN AFRICA
66     WESTERN EUROPE
67     OCEANIA
68     WESTERN EUROPE
69     WESTERN EUROPE
70                 LATIN AMER. & CARIB
71     OCEANIA
72     SUB-SAHARAN AFRICA
73     SUB-SAHARAN AFRICA
74     NEAR EAST
75                    C.W. OF IND. STATES
76     WESTERN EUROPE
77     SUB-SAHARAN AFRICA
78     WESTERN EUROPE
79     WESTERN EUROPE
80     NORTHERN AMERICA
81                 LATIN AMER. & CARIB
82                 LATIN AMER. & CARIB
83     OCEANIA
84                 LATIN AMER. & CARIB
85     WESTERN EUROPE
86     SUB-SAHARAN AFRICA
87     SUB-SAHARAN AFRICA
88                 LATIN AMER. & CARIB
89                 LATIN AMER. & CARIB
90                 LATIN AMER. & CARIB
91           ASIA (EX. NEAR EAST)
92     EASTERN EUROPE
93     WESTERN EUROPE
94           ASIA (EX. NEAR EAST)
95           ASIA (EX. NEAR EAST)
96           ASIA (EX. NEAR EAST)
97     NEAR EAST
98     WESTERN EUROPE
99     WESTERN EUROPE
100    NEAR EAST
101    WESTERN EUROPE
102                LATIN AMER. & CARIB
103          ASIA (EX. NEAR EAST)
104    WESTERN EUROPE
105    NEAR EAST
106                   C.W. OF IND. STATES
107    SUB-SAHARAN AFRICA
108    OCEANIA
109          ASIA (EX. NEAR EAST)
110          ASIA (EX. NEAR EAST)
111    NEAR EAST
112                   C.W. OF IND. STATES
113          ASIA (EX. NEAR EAST)
114    BALTICS
115    NEAR EAST
116    SUB-SAHARAN AFRICA
117    SUB-SAHARAN AFRICA
118    NORTHERN AFRICA
119    WESTERN EUROPE
120    BALTICS
121    WESTERN EUROPE
122          ASIA (EX. NEAR EAST)
123    EASTERN EUROPE
124    SUB-SAHARAN AFRICA
125    SUB-SAHARAN AFRICA
126          ASIA (EX. NEAR EAST)
127          ASIA (EX. NEAR EAST)
128    SUB-SAHARAN AFRICA
129    WESTERN EUROPE
130    OCEANIA
131                LATIN AMER. & CARIB
132    SUB-SAHARAN AFRICA
133    SUB-SAHARAN AFRICA
134    SUB-SAHARAN AFRICA
135                LATIN AMER. & CARIB
136    OCEANIA
137                   C.W. OF IND. STATES
138    WESTERN EUROPE
139          ASIA (EX. NEAR EAST)
140                LATIN AMER. & CARIB
141    NORTHERN AFRICA
142    SUB-SAHARAN AFRICA
143    SUB-SAHARAN AFRICA
144    OCEANIA
145          ASIA (EX. NEAR EAST)
146    WESTERN EUROPE
147                LATIN AMER. & CARIB
148    OCEANIA
149    OCEANIA
150                LATIN AMER. & CARIB
151    SUB-SAHARAN AFRICA
152    SUB-SAHARAN AFRICA
153    OCEANIA
154    WESTERN EUROPE
155    NEAR EAST
156          ASIA (EX. NEAR EAST)
157    OCEANIA
158                LATIN AMER. & CARIB
159    OCEANIA
160                LATIN AMER. & CARIB
161                LATIN AMER. & CARIB
162          ASIA (EX. NEAR EAST)
163    EASTERN EUROPE
164    WESTERN EUROPE
165                LATIN AMER. & CARIB
166    NEAR EAST
167    SUB-SAHARAN AFRICA
168    EASTERN EUROPE
169                   C.W. OF IND. STATES
170    SUB-SAHARAN AFRICA
171    SUB-SAHARAN AFRICA
172                LATIN AMER. & CARIB
173                LATIN AMER. & CARIB
174    NORTHERN AMERICA
175                LATIN AMER. & CARIB
176    OCEANIA
177    WESTERN EUROPE
178    SUB-SAHARAN AFRICA
179    NEAR EAST
180    SUB-SAHARAN AFRICA
181    EASTERN EUROPE
182    SUB-SAHARAN AFRICA
183    SUB-SAHARAN AFRICA
184          ASIA (EX. NEAR EAST)
185    EASTERN EUROPE
186    EASTERN EUROPE
187    OCEANIA
188    SUB-SAHARAN AFRICA
189    SUB-SAHARAN AFRICA
190    WESTERN EUROPE
191          ASIA (EX. NEAR EAST)
192    SUB-SAHARAN AFRICA
193                LATIN AMER. & CARIB
194    SUB-SAHARAN AFRICA
195    WESTERN EUROPE
196    WESTERN EUROPE
197    NEAR EAST
198          ASIA (EX. NEAR EAST)
199                   C.W. OF IND. STATES
200    SUB-SAHARAN AFRICA
201          ASIA (EX. NEAR EAST)
202    SUB-SAHARAN AFRICA
203    OCEANIA
204                LATIN AMER. & CARIB
205    NORTHERN AFRICA
206    NEAR EAST
207                   C.W. OF IND. STATES
208                LATIN AMER. & CARIB
209    OCEANIA
210    SUB-SAHARAN AFRICA
211                   C.W. OF IND. STATES
212    NEAR EAST
213    WESTERN EUROPE
214    NORTHERN AMERICA
215                LATIN AMER. & CARIB
216                   C.W. OF IND. STATES
217    OCEANIA
218                LATIN AMER. & CARIB
219          ASIA (EX. NEAR EAST)
220                LATIN AMER. & CARIB
221    OCEANIA
222    NEAR EAST
223    NORTHERN AFRICA
224    NEAR EAST
225    SUB-SAHARAN AFRICA
226    SUB-SAHARAN AFRICA
Name: Region, dtype: str

In [34]:
df2.columns

Index(['Country', 'Region'], dtype='str')

In [35]:
df2.shape

(227, 2)

In [37]:
df2.loc[225]

Country                                Zambia
Region     SUB-SAHARAN AFRICA
Name: 225, dtype: str

In [38]:
df2.iloc[2]

Country                               Algeria
Region     NORTHERN AFRICA
Name: 2, dtype: str