In [1]:
import pandas as pd

In [35]:
df=pd.read_excel(r"C:\Users\sozma\OneDrive\Attachments\Documents\A1.data analyst course\pandas\Customer Call List.xlsx")

In [36]:
df=df.drop_duplicates()

In [37]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [38]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='str')

In [39]:
df = df.drop(columns='Not_Useful_Column')

In [40]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [41]:
df["Last_Name"].str.strip()

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: str

In [18]:
df["Last_Name"]=df["Last_Name"].str.strip()

In [19]:
df["Last_Name"]=df["Last_Name"].str.lstrip("...")

In [86]:
df["Last_Name"]=df["Last_Name"].str.rstrip("_")

In [87]:
df["Last_Name"]=df["Last_Name"].str.lstrip("/")

In [22]:
df["Last_Name"].str.strip()

0        Baggins
1          Nadir
2          White
3        Schrute
4           Snow
5        Swanson
6         Winger
7         Holmes
8            NaN
9         Parker
10        Gamgee
11        Potter
12        Draper
13         Knope
14    Flenderson
15       Weasley
16         Scott
17          Kent
18        Braton
19     Skywalker
Name: Last_Name, dtype: str

In [50]:
df["Phone_Number"] = df["Phone_Number"].astype(str)

In [51]:
df["Phone_Number"] = df["Phone_Number"].str.replace(r'[^0-9]', '', regex=True)

In [52]:
df["Phone_Number"] = df["Phone_Number"].apply(
    lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10]
    if len(x) == 10 else x
)

In [53]:
df["Phone_Number"]=df["Phone_Number"].apply(lambda x:str(x))

In [54]:
df["Phone_Number"] = df["Phone_Number"].str.replace('NAN', ' ')

In [58]:
df["Phone_Number"].str.strip()

0     123-545-5421
1     123-643-9775
3     123-543-2345
4     876-678-3469
5     304-762-2467
7     876-678-3469
9     123-545-5421
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
19    876-678-3469
Name: Phone_Number, dtype: str

In [56]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [57]:
df = df[df["Phone_Number"] != '']

In [59]:
df["Phone_Number"].str.strip()

0     123-545-5421
1     123-643-9775
3     123-543-2345
4     876-678-3469
5     304-762-2467
7     876-678-3469
9     123-545-5421
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
19    876-678-3469
Name: Phone_Number, dtype: str

In [60]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [ ]:
df[["Street_adress","state","zip_code"]]=df["Address"].str.split(',', n=1, expand=True)

In [68]:
df[["Street_address", "State", "Zip_code"]] = df["Address"].str.split(',', n=2, expand=True)

In [69]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_adress,state,zip_code,Street_address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,NaN,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,NaN,NaN,93 West Main Street,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,NaN,NaN,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,NaN,NaN,768 City Parkway,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,NaN,NaN,98 Clue Drive,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,NaN,25th Main Street,New York,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,NaN,NaN,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,NaN,NaN,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,NaN,NaN,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,NaN,NaN,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,NaN,121 Paper Avenue,Pennsylvania,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,NaN,910 Tatooine Road,Tatooine,NaN

In [70]:
df["Paying Customer"]=df["Paying Customer"].str.replace("Yes","Y")

In [71]:
df["Paying Customer"]=df["Paying Customer"].str.replace("No","N")

In [72]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_adress,state,zip_code,Street_address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,NaN,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,93 West Main Street,NaN,NaN,93 West Main Street,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,NaN,NaN,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,768 City Parkway,NaN,NaN,768 City Parkway,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,NaN,NaN,98 Clue Drive,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,25th Main Street,New York,NaN,25th Main Street,New York,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,NaN,NaN,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,343 City Parkway,NaN,NaN,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,NaN,NaN,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,NaN,NaN,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,NaN,121 Paper Avenue,Pennsylvania,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,NaN,910 Tatooine Road,Tatooine,NaN

In [73]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("Yes","Y")

In [74]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("No","N")

In [75]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_adress,state,zip_code,Street_address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,NaN,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,NaN,NaN,93 West Main Street,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,NaN,NaN,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,NaN,NaN,768 City Parkway,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,NaN,NaN,98 Clue Drive,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,NaN,25th Main Street,New York,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,NaN,NaN,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,NaN,NaN,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,NaN,NaN,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,NaN,NaN,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,NaN,121 Paper Avenue,Pennsylvania,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,NaN,910 Tatooine Road,Tatooine,NaN

In [76]:
df=df.replace('N/A',' ')

In [77]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_adress,state,zip_code,Street_address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,NaN,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,NaN,NaN,93 West Main Street,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,NaN,NaN,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,NaN,NaN,768 City Parkway,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,NaN,NaN,98 Clue Drive,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,NaN,25th Main Street,New York,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,NaN,NaN,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,NaN,NaN,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,NaN,NaN,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,NaN,NaN,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,NaN,121 Paper Avenue,Pennsylvania,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,NaN,910 Tatooine Road,Tatooine,NaN

In [78]:
df = df.drop(columns=['Street_adress', 'state', 'zip_code'])

In [79]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Street_address', 'State',
       'Zip_code'],
      dtype='str')

In [80]:
df = df.drop(columns='Address')

In [81]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,NaN
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,NaN
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,NaN

In [82]:
df = df.reset_index(drop=True)

In [83]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,NaN,NaN
2,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
3,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
4,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,NaN,NaN
5,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
6,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,NaN
7,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,NaN,NaN
8,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,NaN,NaN
9,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,NaN,NaN
10,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,NaN,NaN
11,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,NaN
12,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,NaN

In [84]:
df["Last_Name"] = df["Last_Name"].str.replace('_', '', regex=False)

In [85]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,NaN,NaN
2,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
3,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
4,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,NaN,NaN
5,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
6,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,NaN
7,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,NaN,NaN
8,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,NaN,NaN
9,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,NaN,NaN
10,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,NaN,NaN
11,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,NaN
12,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,NaN