In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\sozma\OneDrive\Attachments\Documents\A1.data analyst course\pandas\world_population.csv")

In [3]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [4]:
df=pd.read_csv(r"C:\Users\sozma\OneDrive\Attachments\Documents\A1.data analyst course\pandas\world_population.csv",index_col='Country')

In [5]:
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [6]:
df.reset_index(inplace=True)

In [7]:
df

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [9]:
df[df['Country'] == 'Yemen']

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42

In [11]:
df.iloc[5]

Country                            Angola
Rank                                   42
CCA3                                  AGO
Capital                            Luanda
Continent                          Africa
2022 Population                35588987.0
2020 Population                33428485.0
2015 Population                28127721.0
2010 Population                23364185.0
2000 Population                16394062.0
1990 Population                11828638.0
1980 Population                 8330047.0
1970 Population                 6029700.0
Area (km²)                      1246700.0
Density (per km²)                 28.5466
Growth Rate                        1.0315
World Population Percentage          0.45
Name: 5, dtype: object

In [12]:
df.reset_index(inplace=True)

In [13]:
df.set_index(['Country','Continent'],inplace=True)

In [14]:
df.sort_index(ascending=True)

,,index,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,Continent,,,,,,,,,,,,,,,,
Afghanistan,Asia,0,36,AFG,Kabul,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,Europe,1,138,ALB,Tirana,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,Africa,2,34,DZA,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,Oceania,3,213,ASM,Pago Pago,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,Europe,4,203,AND,Andorra la Vella,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,Oceania,229,226,WLF,Mata-Utu,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,Africa,230,172,ESH,El Aaiún,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,Asia,231,46,YEM,Sanaa,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,Africa,232,63,ZMB,Lusaka,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,Africa,233,74,ZWE,Harare,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [22]:
pd.set_option('display.max_rows', 235)

In [23]:
df

,,index,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,Continent,,,,,,,,,,,,,,,,
Afghanistan,Asia,0,36,AFG,Kabul,4.112877e+07,3.897223e+07,3.375350e+07,2.818967e+07,1.954298e+07,1.069480e+07,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,Europe,1,138,ALB,Tirana,2.842321e+06,2.866849e+06,2.882481e+06,2.913399e+06,3.182021e+06,3.295066e+06,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,Africa,2,34,DZA,Algiers,4.490322e+07,4.345167e+07,3.954315e+07,3.585634e+07,3.077462e+07,2.551807e+07,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,Oceania,3,213,ASM,Pago Pago,4.427300e+04,4.618900e+04,5.136800e+04,5.484900e+04,5.823000e+04,4.781800e+04,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,Europe,4,203,AND,Andorra la Vella,7.982400e+04,7.770000e+04,7.174600e+04,7.151900e+04,6.609700e+04,5.356900e+04,35611.0,19860.0,468.0,170.5641,1.0100,0.00
Angola,Africa,5,42,AGO,Luanda,3.558899e+07,3.342848e+07,2.812772e+07,2.336418e+07,1.639406e+07,1.182864e+07,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Anguilla,North America,6,224,AIA,The Valley,1.585700e+04,1.558500e+04,1.452500e+04,1.317200e+04,1.104700e+04,8.316000e+03,6560.0,6283.0,91.0,174.2527,1.0066,0.00
Antigua and Barbuda,North America,7,201,ATG,Saint John’s,9.376300e+04,9.266400e+04,8.994100e+04,8.569500e+04,7.505500e+04,6.332800e+04,64888.0,64516.0,442.0,212.1335,1.0058,0.00
Argentina,South America,8,33,ARG,Buenos Aires,4.551032e+07,4.503603e+07,4.325706e+07,4.110012e+07,3.707077e+07,3.263766e+07,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
Armenia,Asia,9,140,ARM,Yerevan,2.780469e+06,2.805608e+06,2.878595e+06,2.946293e+06,3.168523e+06,3.556539e+06,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03
Aruba,North America,10,198,ABW,Oranjestad,1.064450e+05,1.065850e+05,1.042570e+05,1.003410e+05,8.910100e+04,6.571200e+04,62267.0,59106.0,180.0,591.3611,0.9991,0.00
Australia,Oceania,11,55,AUS,Canberra,2.617741e+07,2.567005e+07,2.382024e+07,2.201917e+07,1.901796e+07,1.704800e+07,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33
Austria,Europe,12,99,AUT,Vienna,8.939617e+06,8.907777e+06,8.642421e+06,8.362829e+06,8.010428e+06,7.678729e+06,7547561.0,7465301.0,83871.0,106.5877,1.0020,0.11
Azerbaijan,Asia,13,91,AZE,Baku,1.035807e+07,NaN,9.863480e+06,9.237202e+06,8.190337e+06,7.427836e+06,6383060.0,5425317.0,86600.0,119.6082,1.0044,0.13
Bahamas,North America,14,176,BHS,Nassau,4.099840e+05,4.064710e+05,3.926970e+05,3.732720e+05,3.250140e+05,2.706790e+05,223752.0,179129.0,13943.0,29.4043,1.0051,0.01
Bahrain,Asia,15,154,BHR,Manama,1.472233e+06,1.477469e+06,1.362142e+06,1.213645e+06,7.114420e+05,5.174180e+05,362595.0,222555.0,765.0,1924.4876,1.0061,0.02
Bangladesh,Asia,16,8,BGD,Dhaka,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
Barbados,North America,17,186,BRB,Bridgetown,2.816350e+05,2.806930e+05,2.780830e+05,2.747110e+05,2.646570e+05,2.588680e+05,253575.0,241397.0,430.0,654.9651,1.0015,0.00
Belarus,Europe,18,96,BLR,Minsk,9.534954e+06,9.633740e+06,9.700609e+06,9.731427e+06,1.025648e+07,1.042852e+07,9817257.0,9170786.0,207600.0,45.9295,0.9955,0.12
Belgium,Europe,19,81,BEL,Brussels,1.165593e+07,1.156172e+07,1.124830e+07,1.087795e+07,1.026434e+07,9.959560e+06,9828986.0,9629376.0,30528.0,381.8111,1.0038,0.15
Belize,North America,20,177,BLZ,Belmopan,4.052720e+05,3.949210e+05,3.598710e+05,3.221060e+05,2.404060e+05,1.825890e+05,145133.0,120905.0,22966.0,17.6466,1.0131,0.01
Benin,Africa,21,77,BEN,Porto-Novo,1.335286e+07,1.264312e+07,1.093278e+07,9.445710e+06,6.998023e+06,5.133419e+06,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
Bermuda,North America,22,206,BMU,Hamilton,6.418400e+04,6.403100e+04,6.314400e+04,6.344700e+04,6.137100e+04,5.747000e+04,53565.0,52019.0,54.0,1188.5926,1.0000,0.00
Bhutan,Asia,23,165,BTN,Thimphu,7.824550e+05,7.725060e+05,7.432740e+05,7.055160e+05,5.872070e+05,5.584420e+05,415257.0,298894.0,38394.0,20.3796,1.0064,0.01
Bolivia,South America,24,80,BOL,Sucre,1.222411e+07,1.193616e+07,1.109008e+07,1.022327e+07,8.592656e+06,7.096194e+06,5736088.0,4585693.0,1098581.0,11.1272,1.0120,0.15
Bosnia and Herzegovina,Europe,25,137,BIH,Sarajevo,3.233526e+06,3.318407e+06,3.524324e+06,3.811088e+06,4.179350e+06,4.494310e+06,4199820.0,3815561.0,51209.0,63.1437,0.9886,0.04
Botswana,Africa,26,144,BWA,Gaborone,2.630296e+06,2.546402e+06,2.305171e+06,2.091664e+06,1.726985e+06,1.341474e+06,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
Brazil,South America,27,7,BRA,Brasilia,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
British Virgin Islands,North America,28,221,VGB,Road Town,3.130500e+04,3.091000e+04,2.936600e+04,2.755600e+04,2.010400e+04,1.561700e+04,11109.0,9581.0,151.0,207.3179,1.0059,0.00
Brunei,Asia,29,175,BRN,Bandar Seri Begawan,4.490020e+05,4.417250e+05,4.214370e+05,3.960530e+05,3.339260e+05,2.619280e+05,187921.0,133343.0,5765.0,77.8841,1.0081,0.01
Bulgaria,Europe,30,108,BGR,Sofia,6.781953e+06,6.979175e+06,7.309253e+06,7.592273e+06,8.097691e+06,8.767778e+06,8980606.0,8582950.0,110879.0,61.1654,0.9849,0.09
Burkina Faso,Africa,31,58,BFA,Ouagadougou,2.267376e+07,2.152263e+07,1.871802e+07,1.611684e+07,1.188289e+07,9.131361e+06,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
Burundi,Africa,32,78,BDI,Bujumbura,1.288958e+07,1.222023e+07,1.072715e+07,9.126605e+06,6.307659e+06,5.483793e+06,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
Cambodia,Asia,33,73,KHM,Phnom Penh,1.676784e+07,1.639686e+07,1.541752e+07,1.436353e+07,1.211884e+07,8.910808e+06,6198959.0,6708525.0,181035.0,92.6221,1.0108,0.21
Cameroon,Africa,34,53,CMR,Yaounde,2.791454e+07,2.649109e+07,2.301265e+07,1.987804e+07,1.509159e+07,1.143052e+07,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
Canada,North America,35,39,CAN,Ottawa,3.845433e+07,3.788870e+07,3.573213e+07,3.396341e+07,3.068331e+07,2.765720e+07,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48
Cape Verde,Africa,36,171,CPV,Praia,5.931490e+05,5.826400e+05,5.521660e+05,5.212120e+05,4.582510e+05,3.645630e+05,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
Cayman Islands,North America,37,205,CYM,George Town,6.870600e+04,6.731100e+04,6.091100e+04,5.407400e+04,3.965800e+04,2.602700e+04,17100.0,10533.0,264.0,260.2500,1.0084,0.00
Central African Republic,Africa,38,117,CAF,Bangui,5.579144e+06,5.343020e+06,4.819333e+06,4.660067e+06,3.759170e+06,2.809221e+06,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
Chad,Africa,39,69,TCD,N'Djamena,1.772332e+07,1.664470e+07,1.414027e+07,1.189473e+07,8.259137e+06,5.827069e+06,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
Chile,South America,40,65,CHL,Santiago,1.960373e+07,1.930032e+07,1.787012e+07,1.700416e+07,1.535180e+07,1.334287e+07,11469828.0,9820481.0,756102.0,25.9274,1.0057,0.25
China,Asia,41,1,CHN,Beijing,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
Colombia,South America,42,28,COL,Bogota,5.187402e+07,5.093066e+07,4.711973e+07,NaN,3.921514e+07,3.260139e+07,26176195.0,20905254.0,1141748.0,45.4339,1.0069,0.65
Comoros,Africa,43,163,COM,Moroni,8.367740e+05,8.061660e+05,7.302160e+05,6.560240e+05,5.367580e+05,4.311190e+05,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
Cook Islands,Oceania,44,223,COK,Avarua,1.701100e+04,1.702900e+04,1.769500e+04,1.721200e+04,1.589700e+04,1.712300e+04,17651.0,20470.0,236.0,72.0805,1.0005,0.00
Costa Rica,North America,45,124,CRI,San José,5.180829e+06,5.123105e+06,4.895242e+06,4.622252e+06,3.979193e+06,3.158253e+06,2414303.0,1855697.0,51100.0,101.3861,1.0052,0.06
Croatia,Europe,46,130,HRV,Zagreb,4.030358e+06,4.096868e+06,4.254815e+06,4.368682e+06,4.548434e+06,4.873707e+06,4680144.0,4492638.0,56594.0,71.2153,0.9927,0.05
Cuba,North America,47,85,CUB,Havana,1.121219e+07,1.130070e+07,1.133989e+07,1.129042e+07,1.110579e+07,1.062668e+07,9809107.0,8869636.0,109884.0,102.0366,0.9961,0.14
Curacao,North America,48,189,CUW,Willemstad,1.911630e+05,1.892880e+05,1.695720e+05,1.593800e+05,1.414240e+05,1.554460e+05,156851.0,150385.0,444.0,430.5473,1.0043,0.00
Cyprus,Europe,49,158,CYP,Nicosia,1.251488e+06,1.237537e+06,1.187280e+06,1.129686e+06,9.482370e+05,7.885000e+05,679327.0,640804.0,9251.0,135.2814,1.0059,0.02
Czech Republic,Europe,50,88,CZE,Prague,1.049399e+07,1.053095e+07,1.052380e+07,1.046475e+07,1.023471e+07,1.030119e+07,10270060.0,9795744.0,78865.0,133.0627,0.9984,0.13
Denmark,Europe,51,115,DNK,Copenhagen,5.882261e+06,5.825641e+06,5.677796e+06,5.550849e+06,5.340655e+06,5.144623e+06,5125392.0,4922963.0,43094.0,136.4984,1.0048,0.07
Djibouti,Africa,52,160,DJI,Djibouti,1.120849e+06,1.090156e+06,1.006259e+06,9.191990e+05,7.420330e+05,5.771730e+05,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
Dominica,North America,53,204,DMA,Roseau,7.273700e+04,7.199500e+04,7.000700e+04,6.875500e+04,6.834600e+04,6.948100e+04,72978.0,68895.0,751.0,96.8535,1.0045,0.00
Dominican Republic,North America,54,84,DOM,Santo Domingo,1.122882e+07,1.099966e+07,1.040583e+07,9.775755e+06,8.540791e+06,7.129004e+06,5755800.0,4475871.0,48671.0,230.7087,1.0100,0.14
DR Congo,Africa,55,15,COD,Kinshasa,9.901021e+07,9.285316e+07,7.865690e+07,6.639126e+07,4.861632e+07,3.598754e+07,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
Ecuador,South America,56,67,ECU,Quito,1.800100e+07,1.758860e+07,1.619590e+07,1.498958e+07,1.262651e+07,1.044984e+07,8135845.0,6172215.0,276841.0,65.0229,1.0114,0.23
Egypt,Africa,57,14,EGY,Cairo,1.109901e+08,1.074651e+08,9.772380e+07,8.725241e+07,7.137137e+07,5.721463e+07,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
El Salvador,North America,58,112,SLV,San Salvador,6.336392e+06,6.292731e+06,6.231066e+06,6.114034e+06,5.958482e+06,5.367179e+06,4508992.0,3619090.0,21041.0,301.1450,1.0035,0.08
Equatorial Guinea,Africa,59,152,GNQ,Malabo,1.674908e+06,1.596049e+06,NaN,1.094524e+06,6.849770e+05,4.655490e+05,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
Eritrea,Africa,60,132,ERI,Asmara,3.684032e+06,3.555868e+06,3.340006e+06,3.147727e+06,2.392880e+06,2.149960e+06,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
Estonia,Europe,61,156,EST,Tallinn,1.326062e+06,1.329444e+06,1.314657e+06,1.331535e+06,1.396877e+06,1.570674e+06,1476983.0,1361999.0,45227.0,29.3201,0.9980,0.02
Eswatini,Africa,62,159,SWZ,Mbabane,NaN,1.180655e+06,1.133936e+06,1.099920e+06,1.030496e+06,8.540110e+05,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
Ethiopia,Africa,63,12,ETH,Addis Ababa,1.233799e+08,1.171909e+08,1.024719e+08,8.923779e+07,6.703187e+07,4.787807e+07,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
Falkland Islands,South America,64,231,FLK,Stanley,3.780000e+03,3.747000e+03,3.408000e+03,3.187000e+03,3.080000e+03,2.332000e+03,2240.0,2274.0,12173.0,0.3105,1.0043,0.00
Faroe Islands,Europe,65,209,FRO,Tórshavn,5.309000e+04,5.241500e+04,4.881600e+04,4.841000e+04,4.566000e+04,4.747900e+04,43054.0,38416.0,1393.0,38.1120,1.0038,0.00
Fiji,Oceania,66,162,FJI,Suva,9.297660e+05,9.204220e+05,9.172000e+05,9.051690e+05,8.325090e+05,7.804300e+05,644582.0,527634.0,18272.0,50.8847,1.0056,0.01
Finland,Europe,67,118,FIN,Helsinki,5.540745e+06,5.529468e+06,5.479461e+06,5.363271e+06,5.176209e+06,4.986545e+06,4779418.0,4606621.0,338424.0,16.3722,1.0009,0.07
France,Europe,68,23,FRA,Paris,6.462663e+07,6.448005e+07,6.380977e+07,6.244457e+07,5.866545e+07,5.641290e+07,53713830.0,50523586.0,551695.0,117.1419,1.0015,0.81
French Guiana,South America,69,184,GUF,Cayenne,3.045570e+05,2.909690e+05,2.570260e+05,2.284530e+05,1.643510e+05,1.139310e+05,66825.0,46484.0,83534.0,3.6459,1.0239,0.00
French Polynesia,Oceania,70,183,PYF,Papeete,3.062790e+05,3.019200e+05,2.917870e+05,2.837880e+05,2.509270e+05,2.110890e+05,163591.0,117891.0,4167.0,73.5011,1.0074,0.00
Gabon,Africa,71,146,GAB,Libreville,2.388992e+06,2.292573e+06,2.028517e+06,1.711105e+06,1.272935e+06,9.830280e+05,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
Gambia,Africa,72,142,GMB,Banjul,2.705992e+06,2.573995e+06,2.253133e+06,NaN,NaN,NaN,NaN,NaN,10689.0,253.1567,1.0250,0.03
Georgia,Asia,73,131,GEO,Tbilisi,3.744385e+06,3.765912e+06,3.771132e+06,NaN,NaN,NaN,NaN,NaN,69700.0,53.7214,0.9964,0.05
Germany,Europe,74,19,DEU,Berlin,8.336984e+07,8.332899e+07,8.207323e+07,8.132509e+07,8.155168e+07,7.937020e+07,77786703.0,78294583.0,357114.0,233.4544,0.9995,1.05
Ghana,Africa,75,47,GHA,Accra,3.347587e+07,3.218040e+07,2.887094e+07,2.557472e+07,1.966550e+07,1.544698e+07,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
Gibraltar,Europe,76,219,GIB,Gibraltar,3.264900e+04,3.270900e+04,3.252000e+04,3.126200e+04,2.774100e+04,2.731700e+04,28734.0,26685.0,6.0,5441.5000,0.9994,0.00
Greece,Europe,77,90,GRC,Athens,1.038497e+07,1.051223e+07,1.080664e+07,1.103378e+07,1.103811e+07,1.030226e+07,9307148.0,8544873.0,131990.0,78.6800,0.9942,0.13
Greenland,North America,78,208,GRL,Nuuk,5.646600e+04,5.602600e+04,5.589500e+04,5.635100e+04,5.618400e+04,5.559900e+04,50106.0,45434.0,2166086.0,0.0261,1.0040,0.00
Grenada,North America,79,193,GRD,Saint George's,1.254380e+05,1.236630e+05,1.189800e+05,1.140390e+05,1.074320e+05,9.904700e+04,94838.0,98794.0,344.0,364.6453,1.0066,0.00
Guadeloupe,North America,80,178,GLP,Basse-Terre,3.957520e+05,3.956420e+05,3.990890e+05,4.030720e+05,4.240670e+05,3.919510e+05,334234.0,318310.0,1628.0,243.0909,0.9992,0.00
Guam,Oceania,81,191,GUM,Hagåtña,1.717740e+05,1.692310e+05,1.679780e+05,1.649050e+05,1.601880e+05,1.382630e+05,110286.0,88300.0,549.0,312.8852,1.0073,0.00
Guatemala,North America,82,68,GTM,Guatemala City,1.784391e+07,1.736272e+07,1.600111e+07,1.454312e+07,1.173589e+07,9.084780e+06,6987767.0,5453208.0,108889.0,163.8725,1.0134,0.22
Guernsey,Europe,83,207,GGY,Saint Peter Port,6.330100e+04,6.279400e+04,6.162900e+04,6.078200e+04,5.911400e+04,5.772700e+04,52860.0,52656.0,78.0,811.5513,1.0037,0.00
Guinea,Africa,84,75,GIN,Conakry,1.385934e+07,1.320515e+07,1.162600e+07,1.027073e+07,8.336967e+06,6.354145e+06,4972609.0,4222374.0,245857.0,56.3716,1.0242,0.17
Guinea-Bissau,Africa,85,149,GNB,Bissau,2.105566e+06,2.015828e+06,1.788919e+06,1.567220e+06,1.230849e+06,9.735510e+05,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
Guyana,South America,86,164,GUY,Georgetown,8.087260e+05,7.972020e+05,7.550310e+05,7.479320e+05,7.590510e+05,7.471160e+05,778176.0,705261.0,214969.0,3.7621,1.0052,0.01
Haiti,North America,87,82,HTI,Port-au-Prince,1.158500e+07,1.130680e+07,1.056376e+07,9.842880e+06,8.360225e+06,6.925331e+06,5646676.0,4680812.0,27750.0,417.4773,1.0120,0.15
Honduras,North America,88,89,HND,Tegucigalpa,1.043286e+07,1.012176e+07,9.294505e+06,8.450933e+06,6.656725e+06,5.053234e+06,3777990.0,2782753.0,112492.0,92.7431,1.0150,0.13
Hong Kong,Asia,89,104,HKG,Hong Kong,7.488865e+06,7.500958e+06,7.399838e+06,7.132438e+06,6.731195e+06,5.838574e+06,4978544.0,3955072.0,1104.0,6783.3922,0.9992,0.09
Hungary,Europe,90,94,HUN,Budapest,9.967308e+06,9.750573e+06,9.844246e+06,9.986825e+06,1.020206e+07,NaN,NaN,10315366.0,93028.0,107.1431,1.0265,0.12
Iceland,Europe,91,179,ISL,Reykjavík,3.728990e+05,3.666690e+05,3.310600e+05,3.183330e+05,2.814620e+05,NaN,NaN,204468.0,103000.0,3.6204,1.0069,0.00
India,Asia,92,2,IND,New Delhi,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
Indonesia,Asia,93,4,IDN,Jakarta,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
Iran,Asia,94,17,IRN,Tehran,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,38520664.0,28449705.0,1648195.0,53.7258,1.0071,1.11
Iraq,Asia,95,35,IRQ,Baghdad,4.449612e+07,4.255698e+07,3.775781e+07,3.126488e+07,2.462886e+07,1.765838e+07,13653369.0,9811347.0,438317.0,101.5158,1.0221,0.56
Ireland,Europe,96,125,IRL,Dublin,5.023109e+06,4.946119e+06,4.665760e+06,4.524585e+06,3.768950e+06,3.485374e+06,3391387.0,2937637.0,70273.0,71.4799,1.0073,0.06
Isle of Man,Europe,97,202,IMN,Douglas,8.451900e+04,8.404600e+04,8.359300e+04,8.382800e+04,7.556200e+04,6.886500e+04,64022.0,55298.0,572.0,147.7605,1.0030,0.00
Israel,Asia,98,98,ISR,Jerusalem,9.038309e+06,8.757489e+06,8.007778e+06,7.328445e+06,6.116958e+06,4.803254e+06,3744608.0,2907307.0,20770.0,435.1617,1.0155,0.11
Italy,Europe,99,25,ITA,Rome,5.903747e+07,5.950058e+07,6.023291e+07,5.982245e+07,5.696640e+07,5.675656e+07,56329482.0,53324036.0,301336.0,195.9191,0.9966,0.74
Ivory Coast,Africa,100,52,CIV,Yamoussoukro,2.816054e+07,2.681179e+07,2.359674e+07,2.112004e+07,1.679967e+07,1.191054e+07,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
Jamaica,North America,101,139,JAM,Kingston,2.827377e+06,2.820436e+06,2.794445e+06,2.733896e+06,2.612205e+06,2.392030e+06,2135546.0,1859091.0,10991.0,NaN,NaN,0.04
Japan,Asia,102,11,JPN,Tokyo,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
Jersey,Europe,103,195,JEY,Saint Helier,1.107780e+05,1.083190e+05,1.005610e+05,9.615100e+04,8.619200e+04,8.287400e+04,75124.0,68347.0,116.0,954.9828,1.0106,0.00
Jordan,Asia,104,83,JOR,Amman,1.128587e+07,1.092872e+07,9.494246e+06,6.931258e+06,5.056174e+06,3.480587e+06,2216903.0,1557374.0,89342.0,126.3221,1.0123,0.14
Kazakhstan,Asia,105,66,KAZ,Nursultan,1.939800e+07,1.897924e+07,1.783591e+07,1.662784e+07,1.523625e+07,1.686656e+07,14172710.0,12265305.0,2724900.0,7.1188,1.0105,0.24
Kenya,Africa,106,27,KEN,Nairobi,5.402749e+07,5.198578e+07,4.685149e+07,4.151790e+07,3.085161e+07,2.316227e+07,16187124.0,11473087.0,580367.0,93.0919,1.0193,0.68
Kiribati,Oceania,107,192,KIR,Tarawa,1.312320e+05,1.264630e+05,1.167070e+05,1.079950e+05,8.882600e+04,7.512400e+04,60813.0,57437.0,811.0,161.8150,1.0183,0.00
Kuwait,Asia,108,129,KWT,Kuwait City,4.268873e+06,4.360444e+06,3.908743e+06,2.943356e+06,1.934901e+06,1.674938e+06,1493870.0,802786.0,17818.0,239.5821,1.0044,0.05
Kyrgyzstan,Asia,109,110,KGZ,Bishkek,6.630623e+06,6.424874e+06,5.914980e+06,5.483774e+06,4.935182e+06,4.394734e+06,3691209.0,3016384.0,199951.0,33.1612,1.0158,0.08
Laos,Asia,110,103,LAO,Vientiane,7.529475e+06,7.319399e+06,6.787419e+06,6.323418e+06,5.430853e+06,4.314443e+06,3297519.0,2675283.0,236800.0,31.7968,1.0141,0.09
Latvia,Europe,111,151,LVA,Riga,1.850651e+06,1.897052e+06,1.991955e+06,2.101530e+06,2.392530e+06,2.689391e+06,2572037.0,2397414.0,64559.0,28.6660,0.9876,0.02
Lebanon,Asia,112,119,LBN,Beirut,5.489739e+06,5.662923e+06,6.398940e+06,4.995800e+06,4.320642e+06,3.593700e+06,2963702.0,2381791.0,10452.0,525.2334,0.9816,0.07
Lesotho,Africa,113,147,LSO,Maseru,2.305825e+06,2.254100e+06,2.118521e+06,2.022747e+06,1.998630e+06,1.798997e+06,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
Liberia,Africa,114,121,LBR,Monrovia,5.302681e+06,5.087584e+06,4.612329e+06,4.019956e+06,2.895224e+06,2.209731e+06,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
Libya,Africa,115,107,LBY,Tripoli,6.812341e+06,6.653942e+06,6.192235e+06,6.491988e+06,5.154790e+06,4.236983e+06,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
Liechtenstein,Europe,116,216,LIE,Vaduz,3.932700e+04,3.875600e+04,3.735500e+04,3.592600e+04,3.302600e+04,2.876500e+04,25003.0,21089.0,160.0,245.7937,1.0074,0.00
Lithuania,Europe,117,141,LTU,Vilnius,2.750055e+06,2.820267e+06,2.963765e+06,3.139019e+06,3.599637e+06,3.785847e+06,3521206.0,3210147.0,65300.0,42.1142,0.9869,0.03
Luxembourg,Europe,118,168,LUX,Luxembourg,6.475990e+05,6.303990e+05,5.694080e+05,5.070700e+05,4.356280e+05,3.812670e+05,363741.0,339342.0,2586.0,250.4250,1.0129,0.01
Macau,Asia,119,167,MAC,Concelho de Macau,6.951680e+05,6.762830e+05,6.152390e+05,5.572970e+05,4.318960e+05,3.502270e+05,245332.0,247284.0,30.0,23172.2667,1.0125,0.01
Madagascar,Africa,120,50,MDG,Antananarivo,2.961171e+07,2.822518e+07,2.485091e+07,2.173105e+07,1.621643e+07,1.188276e+07,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37