In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\sozma\OneDrive\Attachments\Documents\A1.data analyst course\pandas\Flavors.csv")

In [4]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [8]:
groupby_frame=df.groupby('Base Flavor')

In [12]:
groupby_frame.mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [13]:
groupby_frame.min(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.2             7.0          15.2
Vanilla                2.3             3.4           5.7

In [14]:
groupby_frame.max(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.8             7.6          16.6
Vanilla               10.0             8.0          18.0

In [16]:
groupby_frame.sum(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [17]:
groupby_frame.count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [18]:
groupby_frame.agg({
    'Flavor Rating': ['max', 'count', 'sum', 'mean'],
    'Texture Rating': ['mean', 'max', 'count', 'sum']
})

            Flavor Rating                  Texture Rating
                      max count   sum mean           mean  max count   sum
Base Flavor
Chocolate             8.8     3  25.2  8.4       7.233333  7.6     3  21.7
Vanilla              10.0     6  34.2  5.7       5.650000  8.0     6  33.9

In [21]:
df.dtypes

Flavor                str
Base Flavor           str
Liked                 str
Flavor Rating     float64
Texture Rating    float64
Total Rating      float64
dtype: object

In [22]:
df.columns

Index(['Flavor', 'Base Flavor', 'Liked', 'Flavor Rating', 'Texture Rating',
       'Total Rating'],
      dtype='str')

In [26]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [28]:
df.groupby(['Base Flavor', 'Liked']).describe()

                  Flavor Rating                                             \
                          count mean       std  min   25%  50%   75%   max
Base Flavor Liked
Chocolate   Yes             3.0  8.4  0.346410  8.2  8.20  8.2  8.50   8.8
Vanilla     No              3.0  3.6  1.212436  2.3  3.05  3.8  4.25   4.7
            Yes             3.0  7.8  1.915724  6.5  6.70  6.9  8.45  10.0

                  Texture Rating            ...            Total Rating  \
                           count      mean  ...   75%  max        count
Base Flavor Liked                           ...
Chocolate   Yes              3.0  7.233333  ...  7.35  7.6          3.0
Vanilla     No               3.0  4.466667  ...  5.00  5.0          3.0
            Yes              3.0  6.833333  ...  7.25  8.0          3.0


                        mean       std   min    25%   50%    75%   max
Base Flavor Liked
Chocolate   Yes    15.700000  0.781025  15.2  15.25  15.3  15.95  16.6
Vanilla     No      8.066667  2.098412   5.7   7.25   8.8   9.25   9.7
            Yes    14.633333  2.950141  12.5  12.95  13.4  15.70  18.0

[3 rows x 24 columns]

In [30]:
df.groupby(['Base Flavor', 'Liked']).mean(numeric_only=True)

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333     15.700000
Vanilla     No               3.6        4.466667      8.066667
            Yes              7.8        6.833333     14.633333